_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 3
                - 55
            "4": 3.10.14
            "5": 0.20.1
            "8":
                - 1
                - 3
            "12": 0.20.1
            "13": windows-amd64
batch_size:
    value: 64
epsilon_decay:
    value: 0.995
epsilon_min:
    value: 0.01
epsilon_start:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
loss_function:
    value: MSELoss
memory_size:
    value: 100000
nsteps:
    value: 2
obs_bars:
    value: 50
optimizer:
    value: RMSprop
sync_freq:
    value: 1000
